workflows:
  ios-workflow:
    name: KMM iOS Workflow
    max_build_duration: 120

    integrations:
      app_store_connect: myapp17247

    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.exam.myapplication

      vars:
        APP_STORE_APPLE_ID: 6759789849
        XCODE_WORKSPACE: "iosApp.xcodeproj"
        XCODE_SCHEME: "iosApp"

    scripts:
      - name: Cocoapods installation
        script: | 
          cd $CM_BUILD_DIR/iosApp
          pod install
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          cd $CM_BUILD_DIR/iosApp
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - iosApp/build/ios/ipa/*.ipa
